"""add user name fields

Revision ID: 0f7962732db9
Revises: b54f96fd0548
Create Date: 2026-01-20 22:41:58.725903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7962732db9'
down_revision: Union[str, Sequence[str], None] = 'b54f96fd0548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('middle_name', sa.String(length=50), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_username'), 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(op.f('uq_users_username'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('user', 'middle_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
