"""init

Revision ID: b54f96fd0548
Revises: 
Create Date: 2026-01-12 13:44:28.589894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54f96fd0548'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('hashed_password', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'GUIDE', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index('ix_users_email', 'user', ['email'], unique=False)
    op.create_index('ix_users_role', 'user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='user')
    op.drop_index('ix_users_email', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
